### ISSUE TITLE
lib file in git

### ISSUE THREAD

**Issue by xtuc** [maurobringolf/webassembly-floating-point-hex-parser#10]
Maybe intentional you commited the transpiled file https://github.com/maurobringolf/webassembly-floating-point-hex-parser/blob/master/lib/index.js

**Comment by maurobringolf** [comment]
Thank you! It was intentional because I thought it was necessary. But if I read the docs correctly `npm build` will be called on every install?

I would definitely prefer to not have it in Git.

**Comment by xtuc** [comment]
I think yarn does it by default (not sure tho), npm does it if you specifiy it as `postinstall` hook.

Usually on my libs I tell the user to run `npm run build / make build` in order to build the project. Before publishing it to npm i run the build (otherwise you will publish nothing, which happens to me so often aha), you can use a make target.

**Comment by maurobringolf** [comment]
Do you need the postinstall hook? I'm not sure how to understand this:

> "This is the plumbing command called by npm link and npm install."

from https://docs.npmjs.com/cli/build. Does that mean when my package is somewhere in the dependency tree and the root gets installed, then my package runs `npm build` too? Thats what I would like it to mean 😁

**Comment by xtuc** [comment]
Note that `npm build` and `npm run build` are two different things, I don't know how to specify a build command for `npm build` but AFAIK it's only for native extensions (which requires to be built on the local machine).

Most of the time packages are already built in the npm registry. Babel for example doesn't requires any additional build step when you require/install it in a project.
